name: Lint

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install development tools
        run: task dependencies:install --output group --output-group-error-only
      - name: Lint
        run: task lint --output group --output-group-error-only
